INSERT INTO users (
  userLevel,
  lastName,
  firstName,
  middleName,
  contactNumber,
  userName,
  pword,
  dateCreated
)
VALUES
  (
    'teacher',
    'Bennett',
    'Seraphina',
    'Hatdog',
    '0932310923',
    'sphia',
    'secretPass',
    CURRENT_DATE
  ),
  (
    'admin',
    'Anderson',
    'Kai',
    'Ko',
    '0907210345',
    'kaio',
    'iDontKnow',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'Smith',
    'Emma',
    'Rose',
    '0912345678',
    'emmarose',
    'password123',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Taylor',
    'Liam',
    'Michael',
    '0987654321',
    'liamteacher',
    'securepass',
    CURRENT_DATE
  ),
  (
    'admin',
    'Harrison',
    'Olivia',
    'Grace',
    '0956789012',
    'oliviag',
    'admin123',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'Davis',
    'Ethan',
    'Daniel',
    '0912233445',
    'ethandavis',
    'studentpass',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Moore',
    'Ava',
    'Elizabeth',
    '0945678901',
    'avamoore',
    'teacher123',
    CURRENT_DATE
  ),
  (
    'admin',
    'Garcia',
    'Mia',
    'Isabella',
    '0990123456',
    'miagarcia',
    'adminpass',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'Johnson',
    'Noah',
    'James',
    '0923456789',
    'noahjohnson',
    'student321',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Brown',
    'Sophia',
    'Emily',
    '0967890123',
    'sophiabrown',
    'teacherpass',
    CURRENT_DATE
  ),
  (
    'admin',
    'Lee',
    'Jackson',
    'Henry',
    '0901234567',
    'jacksonlee',
    'adminpass123',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'White',
    'Oliver',
    'William',
    '0978901234',
    'oliverwhite',
    'mypassword',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Hill',
    'Lily',
    'Grace',
    '0912345678',
    'lilyhill',
    'teacher123',
    CURRENT_DATE
  ),
  (
    'admin',
    'Clark',
    'Lucas',
    'Benjamin',
    '0945678901',
    'lucasclark',
    'adminpass',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'Turner',
    'Chloe',
    'Sophie',
    '0990123456',
    'chloeturner',
    'mypassword',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Carter',
    'Aiden',
    'Caleb',
    '0923456789',
    'aidencarter',
    'teacherpass',
    CURRENT_DATE
  ),
  (
    'admin',
    'King',
    'Ella',
    'Avery',
    '0967890123',
    'ellaking',
    'adminpass',
    CURRENT_DATE
  ),
  (
    'it_admin',
    'Cooper',
    'Mason',
    'Evelyn',
    '0901234567',
    'masoncooper',
    'studentpass',
    CURRENT_DATE
  ),
  (
    'teacher',
    'Hall',
    'Abigail',
    'Liam',
    '0978901234',
    'abigailhall',
    'teacher123',
    CURRENT_DATE
  ),
  (
    'admin',
    'Morgan',
    'Jackson',
    'Aiden',
    '0912345678',
    'jacksonmorgan',
    'adminpass',
    CURRENT_DATE
  );
